name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '0.13.5'

    - name: Terraform Init
      run: terraform init

    - name: Terraform plan
      run: terraform  plan 

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Build Docker image
      run: docker build -t express-app .

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag and push Docker image to ECR
      run: |
        docker tag express-app:latest ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/express-app:latest
        docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/express-app:latest

    - name: Update ECS service
      run: |
        # Use the AWS CLI to update the ECS service
        aws ecs update-service --cluster myapp-cluster --service myapp-service --force-new-deployment
